### ISSUE TITLE
Create a model for products

### ISSUE THREAD

**Issue by Devonnew** [Drop-It-Like-Its-Propane/strickland-propane#4] opened 2021-09-21 17:24 UTC
Create a SQL model for the products which should include
- [ ] name
- [ ] description
- [ ] url
- [ ] quantity
- [ ] product image
- [ ] is in cart
- [ ] tags

**Comment by ItsEducational** [comment] 2021-09-22 22:28
duplicate of #66. Won't fix

**Closed by ItsEducational** 2021-09-22 22:28 UTC
Labels: SQL, Tier 1
